services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task3
    container_name: softy_pinko_backend
    ports:
      - "5252:5252"

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task3
    container_name: softy_pinko_frontend
    ports:
      - "9000:9000"
    depends_on:
      - backend
